backtrack/backtrack/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('productbacklog.urls', namespace='home')),
    path('productbacklog/', include('productbacklog.urls', namespace='productbacklog')),
    path('sprintbacklog/', include('sprintbacklog.urls', namespace='sprintbacklog')),
    path('login/', include('userprofile.urls', namespace='userprofile')),
]

backtrack/sprintbacklog/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'sprintbacklog'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('addsprintview/',views.CreateSprintView.as_view(), name="addsprintview"),
    path('', views.sprint_list, name="sprintlist"),
    path('addsbi/<int:id>/', views.add_sbi, name="addsbi"),
    path('sbilist/<int:id>/', views.sbi_list, name="sbilist"),
    path('addtask/<int:id>/', views.add_task, name="addtask"),
]

backtrack/sprintbacklog/models.py
from django.db import models
from django.utils import timezone
from userprofile.models import Team, User
from productbacklog.models import Product, ProductBacklogItem

# Create your models here.
NOTSTART = 'N'
INPROGRESS = 'P'
COMPLETE = 'C'
PROGRESS_STATUS = (
    (NOTSTART, 'not start'),
    (INPROGRESS, 'in progress'),
    (COMPLETE, 'complete'),
)

class Sprint (models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    number = models.IntegerField()
    created = models.DateTimeField(default=timezone.now)
    progress = models.CharField(
        max_length=1,
        choices=PROGRESS_STATUS,
        default=NOTSTART,
        blank=False,
    )
    deadline = models.DateTimeField()

    def __str__(self):
        return '{product} Sprint {number}'.format(product=self.product, number=self.number)

class SprintBacklogItem (models.Model):
    sprint = models.ForeignKey(Sprint, on_delete=models.CASCADE)
    productbacklogitem = models.ForeignKey(ProductBacklogItem, on_delete=models.CASCADE)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.productbacklogitem.name

class Task (models.Model):
    name = models.CharField(max_length=20, blank=True)
    sprintbacklogitem = models.ForeignKey(SprintBacklogItem, on_delete=models.CASCADE)
    description = models.CharField(max_length=200)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    effort = models.IntegerField()
    progress = models.CharField(
        max_length=1,
        choices=PROGRESS_STATUS,
        default=NOTSTART,
        blank=False,
    )

    def __str__(self):
        return self.name

backtrack/sprintbacklog/forms.py
from django import forms
from .models import Sprint, SprintBacklogItem, Task
from bootstrap_datepicker_plus import DatePickerInput


class AddSprintForm(forms.ModelForm):
    class Meta:
        model = Sprint
        fields = ['number', 'team', 'product','deadline']
        widgets = {
            'deadline': DatePickerInput(), # default date-format %m/%d/%Y will be used
        }

class AddSBIForm(forms.ModelForm):
    class Meta:
        model = SprintBacklogItem
        fields = ['sprint', 'description']


class AddTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'description', 'effort']

backtrack/sprintbacklog/views.py
from django.shortcuts import render, redirect
from django.db.models import F
from .forms import AddSprintForm, AddSBIForm, AddTaskForm
from django.http import HttpResponse
from django.contrib.auth.models import User
from .models import Sprint, SprintBacklogItem, Task
from productbacklog.models import Product, ProductBacklogItem
from django.views import generic
from bootstrap_datepicker_plus import DatePickerInput

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

@login_required(login_url='/login')
def sprint_list(request):
    sprints = Sprint.objects.all()
    context = {'sprints': sprints}
    return render(request, 'sprintbacklog/list.html',context)

@login_required(login_url='/login')
def sbi_list(request, id):
    target_sprint = Sprint.objects.get(id=id)
    sbi_list = SprintBacklogItem.objects.filter(sprint=target_sprint.id)
    sbi_id_list = []
    for sbi in sbi_list:
        sbi_id_list.append(sbi.id)
    print(sbi_id_list)
    task_list = Task.objects.filter(sprintbacklogitem__in=sbi_id_list)
    for task in task_list:
        print(task)
    context = {'sbi_list': sbi_list, 'task_list': task_list, 'sprint_number': target_sprint.number}
    return render(request, 'sprintbacklog/sbilist.html',context)


class CreateSprintView(generic.edit.CreateView):
    model = Sprint
    form_class = AddSprintForm
    template_name = 'sprintbacklog/createsprintview.html'
    success_url="/sprintbacklog/"
    def get_form(self):
         form = super().get_form()
         form.fields['deadline'].widget = DatePickerInput()
         return form
         
@login_required(login_url='/login')
#for testing
# def add_sbi(request, id):
    # target_pbi = ProductBacklogItem.objects.get(id=id)
    # if request.method == "POST":
        # add_sbi_form = AddSBIForm(data=request.POST)
        # if add_sbi_form.is_valid():
            # new_sbi = add_sbi_form.save(commit=False)
            # new_sbi.productbacklogitem = target_pbi
            # target_pbi.progress = 'P'
            # pbi_list = ProductBacklogItem.objects.filter(order__gt=target_pbi.order, product=target_pbi.product)
            # if pbi_list.exists():
                # pbi_list.update(order=F('order')-1)
            # target_pbi.order = 0
            # new_sbi.save()
            # target_pbi.save()
            # return redirect('/productbacklog/orderlist')
        # else:
            # return HttpResponse("The Form is not valid, please post again")
    # else:
        # add_sbi_form = AddSBIForm()
        # sprint_list = Sprint.objects.all()
        # context = {'add_sbi_form': add_sbi_form,'sprint_list': sprint_list, 'target_pbi':target_pbi}
        # return render(request, 'sprintbacklog/createsbi.html', context)

@login_required(login_url='/login')
def add_sbi(request, id):
    target_pbi = ProductBacklogItem.objects.get(id=id)
    if request.method == "GET" or request.method == "POST":
        if checkType(request.user) == "DV":
            teamA = request.user.team.team
            sprint_list = Sprint.objects.filter(product = target_pbi.product, team = teamA).order_by('-number')
            latest_sprint = sprint_list[0]
            print(latest_sprint.progress)
            if latest_sprint.progress == 'N' or latest_sprint.progress == 'P':
                new_sbi = SprintBacklogItem.objects.create(productbacklogitem = target_pbi, sprint = latest_sprint)
                print(new_sbi)
                target_pbi.progress = 'P'
                pbi_list = ProductBacklogItem.objects.filter(order__gt=target_pbi.order, product=target_pbi.product)
                if pbi_list.exists():
                    pbi_list.update(order=F('order')-1)
                target_pbi.order = 0
                new_sbi.save()
                target_pbi.save()
                return redirect('/productbacklog/orderlist')
            else:
                print("the newest sprint in not either Not Started or In Progress")
        elif checkType(request.user) == "PO":
            return HttpResponse("You are not Developer")
    else:
        return HttpResponse("ONLY POST and GET ALLOWED")
        

@login_required(login_url='/login')
def add_task(request, id):
    target_sbi = SprintBacklogItem.objects.get(id=id)
    if request.method == "POST":
        add_task_form = AddTaskForm(data=request.POST)
        if add_task_form.is_valid():
            new_task = add_task_form.save(commit=False)
            new_task.sprintbacklogitem = target_sbi
            new_task.save()
            return redirect('/sprintbacklog/sbilist/'+str(target_sbi.sprint.number)+'/')
        else:
            return HttpResponse("The Form is not valid, please post again")
    else:
        add_task_form = AddTaskForm()
        context = {'add_task_form': add_task_form, 'target_sbi':target_sbi}
        return render(request, 'sprintbacklog/createtask.html', context)

def checkType(user):
    if user.profile.type == "DV":
        return "DV"
    elif user.profile.type == "PO":
        return "PO"
    else:
        return "unknown"

backtrack/templates/sprintbacklog/createsbi.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} New SBI {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- submit form -->
            <h1>{{target_pbi.name}}</h1>
            <form method="post" action=".">

                {% csrf_token %}
                <!-- title -->
                <div class="form-group">
                    <!-- tag -->
                    <label for="Sprint">Sprint</label>
                    <!-- title box -->
                    <select class="form-control" name="sprint" id="sprint">
                      {% for sprint in sprint_list %}
                      <option value="{{sprint.pk}}">{{ sprint }}</option>
                      {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <!-- tag -->
                    <label for="description">Description</label>
                    <!-- title box -->
                    <input type="text" class="form-control" id="description" name="description">
                </div>
                <!-- submit btn -->
                <button type="submit" class="btn btn-primary">Create</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

backtrack/templates/sprintbacklog/createsprintview.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} New Sprint {% endblock title %}
{% block content %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{{ form.media }}
<form method="post">{% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" value="Save">
</form>

{% endblock content %}

backtrack/templates/sprintbacklog/createtask.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} New Task {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- submit form -->
            <h1>Task in {{target_sbi.productbacklogitem.name}}</h1>
            <form method="post" action=".">

                {% csrf_token %}
                <!-- title -->
                <div class="form-group">
                    <!-- tag -->
                    <label for="name">Name</label>
                    <!-- title box -->
                    <input type="text" class="form-control" id="name" name="name">
                </div>
                <!-- title -->
                <div class="form-group">
                    <!-- tag -->
                    <label for="description">Description</label>
                    <!-- title box -->
                    <input type="text" class="form-control" id="description" name="description">
                </div>
                <!-- title -->
                <div class="form-group">
                    <!-- tag -->
                    <label for="effort">Effort</label>
                    <!-- title box -->
                    <input type="text" class="form-control" id="effort" name="effort">
                </div>
                <!-- submit btn -->
                <button type="submit" class="btn btn-primary">Create</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

backtrack/templates/sprintbacklog/list.html
<!-- extends: declare the file is inherited from base.html -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- write the 'title' defined in base.html -->
{% block title %}
  Sprint List
{% endblock title %}

<!-- write the 'content' defined in base.html  -->
{% block content %}
<!-- define the container of article's title -->
<table class="table">
    <thead>
      <tr>
        <th scope="col">Sprint</th>
        <th scope="col">Product</th>
        <th scope="col">Team</th>
        <th scope="col">Created</th>
        <th scope="col">Progress</th>
        <th scope="col">Deadline</th>
      </tr>
    </thead
    <tbody>
      {% for sprint in sprints %}
      <tr>
        <th scope="row">
          <a href="{% url 'sprintbacklog:sbilist' sprint.id %}">
            {{sprint.number}}
          </a>
        </th>
        <td>{{sprint.product}}</td>
        <td>{{sprint.team}}</td>
        <td>{{sprint.created}}</td>
        <td>{{sprint.progress}}</td>
        <td>{{sprint.deadline}}</td>
      </tr>
      {% endfor %}
    </tbody>
</table>

{% endblock content %}

backtrack/templates/sprintbacklog/sbilist.html
<!-- extends: declare the file is inherited from base.html -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- write the 'title' defined in base.html -->
{% block title %}
    SBI List
{% endblock title %}

<!-- write the 'content' defined in base.html  -->
{% block content %}
<!-- define the container of article's title -->
<h1>Sprint {{sprint_number}}</h1>
<table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Description</th>
        <th scope="col">Task</th>
        <th scope="burndown">Burndown</th>
      </tr>
    </thead>
    <tbody>
      {% for sbi in sbi_list %}
      <tr class="sbi">
        <th scope="row">{{sbi.productbacklogitem.name}}</th>
        <td>{{sbi.description}}</td>

        <td>
          <a href="{% url 'sprintbacklog:addtask' sbi.id %}">
            add task
          </a>
          <table class="class">
            <thead>
              <tr>
                <th scope="col">Name</th>
                <th scope="col">Effort</th>
                <th scope="col">Progress</th>
                <th scope="col">Owner</th>
              </tr>
            </thead>
            <tbody>
              {% for task in task_list %}
              <tr>
                {% if task.sprintbacklogitem == sbi %}
                  <th scope="row">{{task.name}}</th>
                  <th scope="row" class="effort">{{task.effort}}</th>
                  <th scope="row" class="pgs">{{task.progress}}</th>
                  <th scope="row">{{task.owner}}</th>
                {% endif %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </td>
        <td class="burndown"></td>

      </tr>
      {% endfor %}
    </tbody>
</table>
<script type='text/javascript'>

  var body = document.getElementsByTagName("body")[0];
  document.addEventListener("DOMContentLoaded", cal);
  function cal(){
    var sbis = document.getElementsByClassName("sbi");
    for (var i=0; i<sbis.length; i++){
      var burndown = 0;
      var total = 0;
      var effort = sbis[i].getElementsByClassName("effort");
      var pgs = sbis[i].getElementsByClassName("pgs");
      for (var n=0; n<effort.length; n++){
        total = Number(total + Number(effort[n].innerHTML));
        if(pgs[n].innerHTML == 'C'){
          burndown = Number(burndown+ Number(effort[n].innerHTML));
        }
      }
      var vari = total - burndown;
      if (total == 0){
        var perc = 100;
      }else{
        var perc = (vari*100/total).toFixed();
      }
      sbis[i].getElementsByClassName("burndown")[0].innerHTML = vari+' ('+perc+'%)';
    }
  }
</script>

{% endblock content %}