backtrack/backtrack/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('productbacklog.urls', namespace='home')),
    path('productbacklog/', include('productbacklog.urls', namespace='productbacklog')),
    path('sprintbacklog/', include('sprintbacklog.urls', namespace='sprintbacklog')),
    path('login/', include('userprofile.urls', namespace='userprofile')),
]

backtrack/productbacklog/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'productbacklog'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('addproduct/', views.add_product, name="addproduct"),
    path('', views.homepage, name="pbilist"),
    #path('pbicurrentlist/', views.pbi_current_list, name="pbicurrentlist"),
    path('addpbi/', views.add_pbi, name="addpbi"),
    path('fulllist/', views.pbi_list, name="fulllist"),
    path('orderlist/', views.order_list, name="orderlist"),
    path('switchpbi', views.switch_pbi, name="switchpbi"),
    path('deletepbi/', views.delete_pbi, name="deletepbi"),
    path('modifypbi/', views.modify_pbi, name="modifypbi"),
]

backtrack/sprintbacklog/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'sprintbacklog'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('addsprintview/',views.CreateSprintView.as_view(), name="addsprintview"),
    path('', views.sprint_list, name="sprintlist"),
    path('addsbi/<int:id>/', views.add_sbi, name="addsbi"),
    path('sbilist/<int:id>/', views.sbi_list, name="sbilist"),
    path('addtask/<int:id>/', views.add_task, name="addtask"),
]

backtrack/productbacklog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from userprofile.models import Team

# Create your models here.
class Product (models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    created = models.DateTimeField(default=timezone.now)
    progress = models.CharField(max_length=20, default="not_started")
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class ProductBacklogItem (models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
#    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    NOTSTART = 'N'
    INPROGRESS = 'P'
    COMPLETE = 'C'
    PROGRESS_STATUS = (
        (NOTSTART, 'not start'),
        (INPROGRESS, 'in progress'),
        (COMPLETE, 'complete'),
    )

    progress = models.CharField(
        max_length=1,
        choices=PROGRESS_STATUS,
        default=NOTSTART,
        blank=False,
    )

    storypoint = models.IntegerField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    order = models.IntegerField(default=0)
    def __str__(self):
        return self.name

#class ProductBacklogItemOrder (models.Model):
#    productbacklogitem = models.ForeignKey(ProductBacklogItem, on_delete=models.CASCADE, null=True)
#    headpbi = models.ForeignKey(ProductBacklogItem, related_name='headpbi' ,on_delete=models.SET_NULL, null=True)
#    tailpbi = models.ForeignKey(ProductBacklogItem, related_name='tailpbi', on_delete=models.SET_NULL, null=True)
#    def __str__(self):
#        return self.productbacklogitem.name

backtrack/productbacklog/forms.py
from django import forms
from .models import Product,ProductBacklogItem

class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ( 'name',)

class AddPBIForm(forms.ModelForm):
    class Meta:
        model = ProductBacklogItem
        fields = ( 'name', 'description', 'storypoint')

class ProductBacklogForm(forms.ModelForm):
    class Meta:
        model = ProductBacklogItem
        fields = ( 'name', 'storypoint', 'description')

backtrack/productbacklog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models import F
from .forms import AddProductForm, AddPBIForm, ProductBacklogForm
from userprofile.models import Profile
from django.http import HttpResponse
from django.contrib.auth.models import User
from .models import Product, ProductBacklogItem

# Create your views here.

@login_required(login_url='/login')
def add_product(request):
    if request.user.profile.type == 'PO':
        if request.method == "POST":
            add_product_form = AddProductForm(data=request.POST)
            if add_product_form.is_valid():
                new_product = add_product_form.save(commit=False)
                new_product.owner = User.objects.get(id = request.user.id)
                new_product.save()
                return redirect('/')
            else:
                return HttpResponse("The Form is not valid, please post again")
        else:
            add_product_form = AddProductForm()
            context = { 'add_product_form': add_product_form }
            return render(request, 'productbacklog/create.html', context)
    else:
        return HttpResponse("You are not Product Owner!")

@login_required(login_url='/login')
def pbi_current_list(request):
    pbis = ProductBacklogItem.objects.filter(progress = 'N')
    context = {'pbis': pbis}
    return render(request, 'productbacklog/currentlist.html', context)
    
@login_required(login_url='/login')
def homepage(request):
    if Profile.objects.filter(user_id=request.user.id).exists():
        profile = Profile.objects.get(user_id=request.user)
    else:
        profile = Profile.objects.create(user=request.user)
    if profile.type == 'PO':
        return redirect('/productbacklog/orderlist/')
    elif profile.type == 'DV':
        return redirect('/sprintbacklog/')
    else:
        return HttpResponse("Your User is not either Developer or Product Owner")

@login_required(login_url='/login')
def pbi_list(request):
    pbis = ProductBacklogItem.objects.all()
    print(request.user)
    if Profile.objects.filter(user_id=request.user.id).exists():
        profile = Profile.objects.get(user_id=request.user)
    else:
        profile = Profile.objects.create(user=request.user)
    #PO DV
    print(profile.type)
    context = {'pbis': pbis}
    return render(request, 'productbacklog/list.html', context)

@login_required(login_url='/login')
def order_list(request):
    # pbis = ProductBacklogItemOrder.objects.filter(productbacklogitem__product__name = 'helloword')
    # order_list = []
    # for pbi in pbis:
    #     if pbi.headpbi == None:
    #         order_list.append(pbi)
    #         while True:
    #             if pbi.tailpbi == None:
    #                 break
    #             pbi = ProductBacklogItemOrder.objects.get(productbacklogitem=pbi.tailpbi)
    #             order_list.append(pbi)
    order_list = ProductBacklogItem.objects.filter(order__gt=0, product__name='helloword').order_by('order')
    context = {'pbis': order_list}
    return render(request, 'productbacklog/orderlist.html', context)

@login_required(login_url='/login')
def add_pbi(request):
    if request.method == "POST":
        add_pbi_form = AddPBIForm(data=request.POST)
        if add_pbi_form.is_valid():
            new_pbi = add_pbi_form.save(commit=False)
            new_pbi.owner = User.objects.get(id = 1)
            new_pbi.product = Product.objects.get(name = "helloword")
            new_pbi.save()
            target_pbi = request.POST.get('follow')
            order_list = ProductBacklogItem.objects.filter(order__gt=0, product__name='helloword')
            if not order_list.exists():
                new_pbi.order = 1
                new_pbi.save()
            elif target_pbi =='':
                order_list = ProductBacklogItem.objects.filter(order__gt=0, product__name='helloword')
                order_list.update(order=F('order')+1)
                new_pbi.order = 1
                new_pbi.save()
            else:
                target_pbi_object = ProductBacklogItem.objects.get(id=target_pbi)
                order_list = ProductBacklogItem.objects.filter(order__gt=target_pbi_object.order,product__name='helloword')
                order_list.update(order=F('order')+1)
                new_pbi.order = target_pbi_object.order+1
                new_pbi.save()
            return redirect('/productbacklog/')
            #order_list = ProductBacklogItemOrder.objects.filter(productbacklogitem__product=new_pbi.product)
            #print(order_list)
            # target_pbi = request.POST.get('follow')
            # order_list = ProductBacklogItem.objects.filter(order>0, product=target_pbi.product)
            #if len(order_list)==0:
                # new_order = ProductBacklogItemOrder(
                #     productbacklogitem = new_pbi,
                #     headpbi = None,
                #     tailpbi = None,
                # )
                # new_order.save()
            #elif target_pbi == '':
                #head = ProductBacklogItemOrder.objects.filter(headpbi = None, productbacklogitem__product = new_pbi.product)[0]
                # new_order = ProductBacklogItemOrder(
                #     productbacklogitem = new_pbi,
                #     headpbi = None,
                #     tailpbi = head.productbacklogitem,
                # )
                # new_order.save()
                # head.headpbi = new_order.productbacklogitem
                # head.save()
            #else:
                #head = ProductBacklogItemOrder.objects.get(productbacklogitem = target_pbi)
                # try:
                #     tail = ProductBacklogItemOrder.objects.get(headpbi = target_pbi)
                # except ProductBacklogItemOrder.DoesNotExist:
                #     tail = None
                # if tail != None:
                #     new_order = ProductBacklogItemOrder(
                #         productbacklogitem = new_pbi,
                #         headpbi = head.productbacklogitem,
                #         tailpbi = head.tailpbi,
                #     )
                #     head.tailpbi = new_order.productbacklogitem
                #     tail.headpbi = new_order.productbacklogitem
                #     new_order.save()
                #     head.save()
                #     tail.save()
                # else:
                #     new_order = ProductBacklogItemOrder(
                #         productbacklogitem = new_pbi,
                #         headpbi = head.productbacklogitem,
                #         tailpbi = None,
                #     )
                #     head.tailpbi = new_order.productbacklogitem
                #     new_order.save()
                #     head.save()
                #     return redirect('/productbacklog/')
        else:
            HttpResponse("The Form is not valid, please post again")
    else:
        add_pbi_form = AddPBIForm()
        pbi_list = ProductBacklogItem.objects.filter(order__gt=0).filter(product = Product.objects.get(name = "helloword").id).order_by('order')
        context = {'add_pbi_form': add_pbi_form, 'pbi_list':pbi_list}
        return render(request, 'productbacklog/createpbi.html', context)
        
@login_required(login_url='/login')
def switch_pbi(request):
    if request.method == "POST":
        #print(request.POST.getlist("switch", None))
        switch_list= request.POST.getlist("switch")
        #print(switch_list[0])
        if len(switch_list) >= 2:
            head = ProductBacklogItem.objects.get(id=switch_list[0])
            tail = ProductBacklogItem.objects.get(id=switch_list[1])
            temp = head.order
            head.order = tail.order
            tail.order = temp
            head.save()
            tail.save()
        # head = ProductBacklogItemOrder.objects.get(productbacklogitem=switch_list[0])
        # tail = ProductBacklogItemOrder.objects.get(productbacklogitem=switch_list[1])
        # temp = tail
        # upper1 = ProductBacklogItemOrder.objects.get(headpbi=switch_list[0])
        # lower1 = ProductBacklogItemOrder.objects.get(tailpbi=switch_list[1])
        # upper1.headpbi = ProductBacklogItem.objects.get(id=switch_list[1])
        # lower1.tailpbi = ProductBacklogItem.objects.get(id=switch_list[0])
        #
        #
        # tail.headpbi = head.headpbi
        # tail.tailpbi = head.tailpbi
        # head.headpbi = temp.headpbi
        # head.tailpbi = temp.tailpbi
        #
        # if ProductBacklogItemOrder.objects.get(productbacklogitem=switch_list[0]).headpbi != None:
        #     upper = ProductBacklogItemOrder.objects.get(tailpbi=switch_list[0])
        #     upper.tailpbi = ProductBacklogItem.objects.get(id=switch_list[1])
        #     if ProductBacklogItemOrder.objects.get(productbacklogitem=switch_list[1]).tailpbi != None:
        #         lower = ProductBacklogItemOrder.objects.get(headpbi=switch_list[1])
        #         lower.headpbi = ProductBacklogItem.objects.get(id=switch_list[0])
        #         lower.save()
        #     upper.save()
        # elif ProductBacklogItemOrder.objects.get(productbacklogitem=switch_list[1]).tailpbi != None:
        #     lower = ProductBacklogItemOrder.objects.get(headpbi=switch_list[1])
        #     lower.headpbi = ProductBacklogItem.objects.get(id=switch_list[0])
        #     lower.save()
        # upper1.save()
        # lower1.save()
        # head.save()
        # tail.save()


    return redirect('/productbacklog/orderlist')
    
@login_required(login_url='/login')
def delete_pbi(request):
    if request.method == "POST":
        pbiId = request.POST.get('id');

backtrack/templates/productbacklog/create.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} New Project {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- submit form -->
            <form method="post" action=".">

                {% csrf_token %}
                <!-- title -->
                <div class="form-group">
                    <!-- tag -->
                    <label for="title">Name</label>
                    <!-- title box -->
                    <input type="text" class="form-control" id="name" name="name">
                </div>

                <!-- submit btn -->
                <button type="submit" class="btn btn-primary">Create</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

backtrack/templates/productbacklog/createpbi.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} New PBI {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- submit form -->
            <form method="post" action=".">

                {% csrf_token %}
                <!-- title -->
                <div class="form-group">
                    <!-- tag -->
                    <label for="title">Name</label>
                    <!-- title box -->
                    <input type="text" class="form-control" id="name" name="name">
                </div>

                <div class="form-group">
                    <!-- tag -->
                    <label for="title">Description</label>
                    <!-- title box -->
                    <input type="text" class="form-control" id="description" name="description">
                </div>

                <div class="form-group">
                    <!-- tag -->
                    <label for="title">Story Point</label>
                    <!-- title box -->
                    <input type="text" class="form-control" id="storypoint" name="storypoint">
                </div>

                <div class="form-group">
                    <!-- tag -->
                    <label for="follow">Follow By</label>
                    <!-- select box -->
                    <select class="form-control" name="follow" id="follow">
                      <option value="">--TOP--</option>
                      {% for pbi in pbi_list %}
                      <option value="{{pbi.pk}}">{{ pbi.name }}</option>
                      {% endfor %}
                    </select>

                <!-- submit btn -->
                <button type="submit" class="btn btn-primary">Create</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

backtrack/templates/productbacklog/currentlist.html
<!-- extends: declare the file is inherited from base.html -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- write the 'title' defined in base.html -->
{% block title %}
    PBI Current View
{% endblock title %}

<!-- write the 'content' defined in base.html  -->
{% block content %}
<!-- define the container of article's title -->
<table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Progress</th>
        <th scope="col">Created Date</th>
        <th scope="col">Story Point</th>
        <th scope="col">Description</th>
      </tr>
    </thead
    <tbody>
      {% for pbi in pbis %}
      <tr>
        <th scope="row">
          <a href="{% url 'sprintbacklog:addsbi' pbi.id %}">
            {{pbi.name}}
          </a>
        </th>
        <td>{{pbi.progress}}</td>
        <td>{{pbi.created}}</td>
        <td>{{pbi.storypoint}}</td>
        <td>{{pbi.description}}</td>
      </tr>
      {% endfor %}
    </tbody>
</table>

{% endblock content %}

backtrack/templates/productbacklog/list.html
<!-- extends: declare the file is inherited from base.html -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- write the 'title' defined in base.html -->
{% block title %}
    PBI Full View
{% endblock title %}

<!-- write the 'content' defined in base.html  -->
{% block content %}
<!-- define the container of article's title -->
<table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Progress</th>
        <th scope="col">Created Date</th>
        <th scope="col">Story Point</th>
        <th scope="col">Description</th>
      </tr>
    </thead
    <tbody>
      {% for pbi in pbis %}
      <tr>
        <th scope="row">{{pbi.name}}</th>
        <td>{{pbi.progress}}</td>
        <td>{{pbi.created}}</td>
        <td>{{pbi.storypoint}}</td>
        <td>{{pbi.description}}</td>
      </tr>
      {% endfor %}
    </tbody>
</table>

{% endblock content %}

backtrack/templates/productbacklog/orderlist - 複製.html
<!-- extends: declare the file is inherited from base.html -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- write the 'title' defined in base.html -->
{% block title %}
    PBI Current View
{% endblock title %}


  </script>
<!-- write the 'content' defined in base.html  -->
{% block content %}
<link rel="stylesheet" href="{% static 'productbacklog/orderlist.css' %}"/>
<script src="{% static 'productbacklog/orderlist.js' %}"></script>
<!-- define the container of article's title -->
{% if user.profile.type == 'PO' %}
<form method="post" action="/productbacklog/switchpbi">
  {% csrf_token %}
  <button id='switchBtn' type="submit" class="btn btn-primary mb-2">switch</button>
  <div class='tSPContainer'><label for='totalStoryPoint'>Total Story Point:</label><div id='totalStoryPoint'></div></div>
{% endif %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">Order</th>
        <th scope="col">Name</th>
        {% if user.profile.type == 'PO' %}
        <th scope="col">Check</th>
        {% endif %}
        <th scope="col">Progress</th>
        <th scope="col">Created Date</th>
        <th scope="col">Story Point</th>
        <th scope="col">Cumlative Point</th>
        <th scope="col">Description</th>
      </tr>
    </thead>
    <tbody>
      {% for pbi in pbis %}
      <tr>
        <th scope="row">{{pbi.order}}</th>
        <th scope="row" action="/productbacklog/switchpbi">
          <a href="{% url 'sprintbacklog:addsbi' pbi.id %}">
            {{pbi.name}}
          </a>
        </th>
        {% if user.profile.type == 'PO' %}
        <div class="form-check">
          <td><input class="form-check-input" type="checkbox" value="{{pbi.id}}" name="switch" id="switch"></td>
        </div>
        {% endif %}
        <td>{{pbi.progress}}</td>
        <td>{{pbi.created}}</td>
        <td class='storyPoint'>{{pbi.storypoint}}</td>
        <td class='cumulativeStoryPoint'></td>
        <td>{{pbi.description}}</td>
      </tr>
      {% endfor %}
    </tbody>
</table>
{% if user.profile.type == 'PO' %}
</form>
{% endif %}
{% endblock content %}

backtrack/templates/productbacklog/orderlist.html
<!-- extends: declare the file is inherited from base.html -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- write the 'title' defined in base.html -->
{% block title %}
    PBI Current View
{% endblock title %}


<!-- write the 'content' defined in base.html  -->
{% block content %}
<link rel="stylesheet" href="{% static 'productbacklog/orderlist.css' %}"/>
<script src="{% static 'productbacklog/orderlist.js' %}"></script>
<!-- define the container of article's title -->
{% if user.profile.type == 'PO' %}
<form method="post" action="/productbacklog/switchpbi">
  {% csrf_token %}
  <button id='switchBtn' type="submit" class="btn btn-primary mb-2 btnInForm">switch</button>
  <a href="/productbacklog/addpbi" class="btn btn-primary mb-2 btnInForm">Add PBI</a>
  {% endif %}
  <div class='tSPContainer'><label for='totalStoryPoint'>Total Story Point:</label><div id='totalStoryPoint'></div></div>
<table class="table">
    <thead>
      <tr>
        <th scope="col">Order</th>
        <th scope="col">Name</th>
        {% if user.profile.type == 'PO' %}
        <th scope="col">Check</th>
        {% endif %}
        <th scope="col">Progress</th>
        <th scope="col">Created Date</th>
        <th scope="col">Story Point</th>
        <th scope="col">Cumlative Point</th>
        <th scope="col">Description</th>
      </tr>
    </thead>
    <tbody>
      {% for pbi in pbis %}
      <tr id={{pbi.id}}>
        <th scope="row">{{pbi.order}}</th>
        {%  if user.profile.type == 'DV' %}
        <th scope="row" action="/productbacklog/switchpbi">
          <a href="{% url 'sprintbacklog:addsbi' pbi.id %}">
            {{pbi.name}}
          </a>
        </th>
        {% endif %}
        {%  if user.profile.type == 'PO' %}
        <th scope="row"">
            <div value={{pbi.id}} class="namePopup" data-toggle="modal" data-target="#myModal" onclick="namePopupFunc(event)">{{pbi.name}}</div>
        </th>
        <div class="form-check">
          <td><input class="form-check-input" type="checkbox" value="{{pbi.id}}" name="switch" id="switch"></td>
        </div>
        {% endif %}
        <td>{{pbi.progress}}</td>
        <td>{{pbi.created}}</td>
        <td class='storyPoint'>{{pbi.storypoint}}</td>
        <td class='cumulativeStoryPoint'></td>
        <td class='description'>{{pbi.description}}</td>
      </tr>
      {% endfor %}
    </tbody>
</table>
{% if user.profile.type == 'PO' %}
</form>

<!-- Modal -->
                <div class="modal fade" id="myModal" role="dialog">
                    <div class="modal-dialog">
                        <!-- Modal content-->
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 id='titleInModal' class="modal-title"></h4>
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                            </div>
                            <div class="modal-body">
                                <form id='modifyPBI' method='POST'>
                                    {% csrf_token %}
                                    <div class="form-group form-inline">
                                        <label class='labelInModal' for='nameInModal'>Name:</label>
                                        <input type="text" class="form-control" id="nameInModal" name="name" value=''>
                                    </div>
                                    <div class="form-group form-inline">
                                        <label class='labelInModal' for='storyPointInModal'>Story Point:</label>
                                        <input type="text" class="form-control" id="storyPointInModal" name="storypoint" value=''>
                                    </div>
                                    <div class="form-group form-inline col-md-8">
                                        <label class='labelInModal' for='descriptionInModal'>Description:</label>
                                        <textarea type="text" class="form-control" id="descriptionInModal" name="description" rows="12" value=''></textarea>
                                    </div>
                                    <input type='text' id='idInModal' name='id' value='' hidden>
                                    <button class="btn btn-primary" id='modifyBtn' onclick='pbi_modify()' >Modify</button>
                                    <button class="btn btn-primary" id='deleteBtn' onclick='pbi_delete()'>Delete</button>
                                    <button id="submit" type="submit" hidden>submit</button>
                                </form>
                            </div>
                        </div>
      
                    </div>
                </div>
{% endif %}
{% endblock content %}